Repository NREL/hercules, pull requests merged in 2023-12, with the labels that each got.

#41 Updating controller to align with WHOC
  .gitignore
  example_case_folders/01_amr_wind_only/batch_script.sh
  example_case_folders/01_amr_wind_only/hercules_runscript.py
  example_case_folders/02_amr_wind_dummy_only/amr_input.inp
  example_case_folders/02_amr_wind_dummy_only/bash_script.sh
  example_case_folders/02_amr_wind_dummy_only/hercules_runscript.py
  example_case_folders/03_amr_wind_and_solar/hercules_runscript.py
  example_case_folders/04_amr_wind_and_solar_and_battery/hercules_runscript.py
  example_case_folders/05_amr_wind_dummy_and_electrolzyer/hercules_runscript.py
  hercules/controller.py
  hercules/controller_standin.py
  hercules/dummy_amr_wind.py
  hercules/emulator.py
Labels: enhancement

#39 Update to public seas
  .github/workflows/continuous-integration-workflow.yaml
  docs/install_old.md
  docs/install_on_kestrel.md
  tests/py_sims_test.py
  tests/seas_test.py
Labels: documentation, enhancement

#30 Feature/battery example
  .gitignore
  example_case_folders/06_amr_wind_standin_and_battery/README.md
  example_case_folders/06_amr_wind_standin_and_battery/amr_input.inp
  example_case_folders/06_amr_wind_standin_and_battery/batch_script.sh
  example_case_folders/06_amr_wind_standin_and_battery/battery_behavior.ipynb
  example_case_folders/06_amr_wind_standin_and_battery/hercules_input_000.yaml
  example_case_folders/06_amr_wind_standin_and_battery/hercules_runscript.py
  example_case_folders/06_amr_wind_standin_and_battery/hercules_runscript_dummy_amr.py
  hercules/controller_standin.py
  hercules/dummy_amr_wind.py
  hercules/emulator.py
  hercules/python_simulators/simple_battery.py
  hercules/tools/generate_amr_standin_data.py
Labels: examples

#59 Add WHOC installation instructions to Hercules documentation
  docs/install_old.md
  docs/install_on_kestrel.md
Labels: documentation
