Repository NREL/hercules, pull requests merged in 2024-03, with the labels that each got.

#87 Refactor example 7
  .github/workflows/deploy-pages.yaml
  docs/_toc.yml
  example_case_folders/06_amr_wind_standin_and_battery/batch_script.sh
  example_case_folders/07_amr_wind_standin_and_solar_pysam/README.md
  example_case_folders/07_amr_wind_standin_and_solar_pysam/batch_script.sh
Labels: examples

#90 Smooth output of FlorisStandin to prevent oscilations in closed-loop response
  hercules/floris_standin.py
  tests/floris_standin_test.py
Labels: bug, enhancement

#93 [BUGFIX] Create outputs folder in examples to avoid error when output file does not exist
  .gitignore
  example_case_folders/02_amr_wind_standin_only/bash_script.sh
  hercules/amr_wind_standin.py
  hercules/emulator.py
Labels: bug

#91 Feature/battery cell model
  .gitignore
  docs/battery.md
  example_case_folders/06_amr_wind_standin_and_battery/bash_script.sh
  example_case_folders/06_amr_wind_standin_and_battery/batch_script.sh
  example_case_folders/06_amr_wind_standin_and_battery/battery_behavior.ipynb
  example_case_folders/06_amr_wind_standin_and_battery/hercules_input_000.yaml
  example_case_folders/06_amr_wind_standin_and_battery/test_read_output.ipynb
  hercules/emulator.py
  hercules/py_sims.py
  hercules/python_simulators/battery.py
  hercules/python_simulators/simple_battery.py
  hercules/tools/generate_amr_standin_data.py
  tests/python_simulators_test/battery_test.py
  tests/python_simulators_test/simple_battery_test.py
Labels: documentation, new-feature
