Repository NREL/hercules, pull requests merged in 2024-02, with the labels that each got.

#66 [BUG] Hotfix: track floris v4 change in input file "turbulence_intensities"
  hercules/floris_standin.py
Labels: bug

#64 simple_battery unit tests
  example_case_folders/06_amr_wind_standin_and_battery/hercules_runscript.py
  tests/python_simulators_test/simple_battery_test.py
Labels: testing

#76 Enable passing power setpoints to wind simulators
  .gitignore
  hercules/amr_wind_standin.py
  hercules/emulator.py
  hercules/floris_standin.py
  tests/emulator_test.py
  tests/floris_standin_test.py
  tests/test_inputs/external_data.csv
Labels: enhancement

#83 [BUGFIX] Update FlorisStandin to use set() run() paradigm introduced in FLORIS v4
  hercules/floris_standin.py
  tests/floris_standin_test.py
Labels: bug, testing

#85 [BUGFIX] Reenable AMR-Wind by setting up empty power_setpoints
  hercules/amr_wind_standin.py
  hercules/emulator.py
Labels: bug

#84 Feature/update example 6
  .github/workflows/check-working-examples.yaml
  docs/_toc.yml
  docs/examples.md
  docs/examples_overview.md
  example_case_folders/06_amr_wind_standin_and_battery/README.md
  example_case_folders/06_amr_wind_standin_and_battery/batch_script.sh
  hercules/amr_wind_standin.py
  hercules/emulator.py
  hercules/floris_standin.py
  setup.py
  tests/emulator_test.py
Labels: documentation, examples
